---
- name: Full Nexus + LVM Blobstore + Nginx + Firewall Setup
  hosts: nexus_servers
  become: true
  
  vars_files:
    - roles/nexus_end_to_end_setup/vars/main.yml

  vars_prompt:
    - name: "device_name"
      prompt: "Enter the block device for blobstore (default: /dev/sdc)"
      private: no
      default: "/dev/sdc"

  pre_tasks:
    - name: 🔍 Check if host is reachable
      ping:
      register: ping_result
      ignore_unreachable: true
      ignore_errors: true

    - name: 🚫 Skip unreachable hosts
      meta: end_host
      when: ping_result is failed

    - name: 📦 Manually gather facts for reachable hosts
      setup:
      when: ping_result is succeeded

    - name: ⏱️  Set unified scan timestamp
      set_fact:
        scan_timestamp: "{{ '%Y%m%d%H%M%S' | strftime }}"
      run_once: true

    - name: Gather OS facts
      setup:
        filter: ansible_distribution*
      tags: always

  tasks:
    - import_tasks: roles/nexus_end_to_end_setup/tasks/nexus.yml
    - import_tasks: roles/nexus_end_to_end_setup/tasks/blobstore.yml
    - import_tasks: roles/nexus_end_to_end_setup/tasks/nginx.yml
    - import_tasks: roles/nexus_end_to_end_setup/tasks/firewall.yml
